# Generated by Django 2.2.7 on 2020-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
